[package]
name = "bevy_game"
version = "0.1.0"
authors = ["Julian Bieber <julian.bieber.1992@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy.git", version = "0.2.1", rev = "5df6804daf056f75872c92800d3312ce71056692"}
physme = "0.2.4"

[patch.crates-io]
bevy = {git = "https://github.com/bevyengine/bevy.git", version = "0.2.1", rev = "5df6804daf056f75872c92800d3312ce71056692"}